export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_TOP__REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP__SUCCESS = "PRODUCT_TOP__SUCCESS";
export const PRODUCT_TOP__FAIL = "PRODUCT_TOP__FAIL";

export const PRODUCT_REDUCE_REQUEST = "PRODUCT_REDUCE_REQUEST";
export const PRODUCT_REDUCE_SUCCESS = "PRODUCT_REDUCE__SUCCESS";
export const PRODUCT_REDUCE_FAIL = "PRODUCT_REDUCE__FAIL";
